/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ProfessionalIndexRouteImport } from './routes/professional.index'
import { Route as ProfessionalAjouterCabinetRouteImport } from './routes/professional.ajouter-cabinet'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as PublicRechercheRouteImport } from './routes/public.recherche'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIndexRoute = ProfessionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalAjouterCabinetRoute =
  ProfessionalAjouterCabinetRouteImport.update({
    id: '/ajouter-cabinet',
    path: '/ajouter-cabinet',
    getParentRoute: () => ProfessionalRoute,
  } as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRechercheRoute = PublicRechercheRouteImport.update({
  id: '/public/recherche',
  path: '/public/recherche',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/signaler': typeof SignalerRoute
  '/api/$': typeof ApiSplatRoute
  '/professional/ajouter-cabinet': typeof ProfessionalAjouterCabinetRoute
  '/public/recherche': typeof PublicRechercheRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/signaler': typeof SignalerRoute
  '/api/$': typeof ApiSplatRoute
  '/professional/ajouter-cabinet': typeof ProfessionalAjouterCabinetRoute
  '/public/recherche': typeof PublicRechercheRoute
  '/professional': typeof ProfessionalIndexRoute
  '/public': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/signaler': typeof SignalerRoute
  '/api/$': typeof ApiSplatRoute
  '/professional/ajouter-cabinet': typeof ProfessionalAjouterCabinetRoute
  '/public/recherche': typeof PublicRechercheRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/professional'
    | '/signaler'
    | '/api/$'
    | '/professional/ajouter-cabinet'
    | '/public/recherche'
    | '/professional/'
    | '/public/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/signaler'
    | '/api/$'
    | '/professional/ajouter-cabinet'
    | '/public/recherche'
    | '/professional'
    | '/public'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/professional'
    | '/signaler'
    | '/api/$'
    | '/professional/ajouter-cabinet'
    | '/public/recherche'
    | '/professional/'
    | '/public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
  SignalerRoute: typeof SignalerRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PublicRechercheRoute: typeof PublicRechercheRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/': {
      id: '/professional/'
      path: '/'
      fullPath: '/professional/'
      preLoaderRoute: typeof ProfessionalIndexRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/ajouter-cabinet': {
      id: '/professional/ajouter-cabinet'
      path: '/ajouter-cabinet'
      fullPath: '/professional/ajouter-cabinet'
      preLoaderRoute: typeof ProfessionalAjouterCabinetRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/public/': {
      id: '/public/'
      path: '/public'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/recherche': {
      id: '/public/recherche'
      path: '/public/recherche'
      fullPath: '/public/recherche'
      preLoaderRoute: typeof PublicRechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfessionalRouteChildren {
  ProfessionalAjouterCabinetRoute: typeof ProfessionalAjouterCabinetRoute
  ProfessionalIndexRoute: typeof ProfessionalIndexRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalAjouterCabinetRoute: ProfessionalAjouterCabinetRoute,
  ProfessionalIndexRoute: ProfessionalIndexRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ProfessionalRoute: ProfessionalRouteWithChildren,
  SignalerRoute: SignalerRoute,
  ApiSplatRoute: ApiSplatRoute,
  PublicRechercheRoute: PublicRechercheRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
